use gamesquare;
INSERT INTO utente values('AkiraHW', 'akirahoward01@gmail.com', 'password1', default, default);
INSERT INTO utente values('DarioTW', 'dariomocciatwitch@gmail.com', 'password2', default, default);
INSERT INTO utente values('DeadOrAlive', 'spinmeround@yahoo.it', 'password3', default, default);
INSERT INTO utente values('Zelda96', 'legendofzelda@gmail.com', 'hyrule01', default, default);
INSERT INTO utente values('Zagreus94', 'zagreus94@libero.it', 'olympus01', default, default);
INSERT INTO utente values('CloudStrife', 'finalfantasy@gmail.com', 'midgar01', default, default);
INSERT INTO utente values('ZackFair', 'unfairzack@libero.it', 'midgar02' , default, 'mod');
INSERT INTO utente values('AerithGain', 'againsborough@yahoo.it', 'midgar03', default, 'mod');
INSERT INTO utente values('AmirRao', 'amiraoSG@gmail.com', 'password4', default, 'dev');
INSERT INTO utente values('AonumaTLOZ', 'eijiaonuma@gmail.com', 'hyrule02', default, 'dev');
INSERT INTO utente values('CynthiaPT', 'pkplatinum@gmail.com', 'sinnoh01', default, 'manager');
INSERT INTO utente values('KomorBW', 'pkblackandwhite@gmail.com', 'unima01', default, 'manager');